In [2]:
print('Hello Abhishek')

Hello Abhishek


In [5]:
import numpy as np
import pandas as pd

In [9]:
np.zeros((3,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full(5,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
np.full((3,5), 2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [17]:
np.array(range(12),dtype='int').reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])